# Generated by Django 4.2.9 on 2024-04-03 05:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField(blank=True, max_length=100)),
                ('gallery', models.URLField(blank=True, default='')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=100)),
                ('species', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Exhibit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Exhibit Title', max_length=255)),
                ('slug', models.CharField(editable=False, help_text='Exhibit Slug', max_length=255)),
                ('description', models.TextField(blank=True, default='', help_text='Exhibit Description')),
                ('rating', models.CharField(choices=[('Clean', 'Clean'), ('Explicit', 'Explicit')], max_length=10)),
                ('visibility', models.CharField(choices=[('Visible', 'Visible'), ('Hidden', 'Hidden')], max_length=8)),
                ('date', models.DateField(blank=True, default=None, null=True)),
                ('artist', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cdosgallery.artist')),
                ('characters', models.ManyToManyField(to='cdosgallery.character')),
                ('images', models.ManyToManyField(to='cdosgallery.image')),
                ('sources', models.ManyToManyField(blank=True, default=None, to='cdosgallery.source')),
            ],
        ),
    ]
