# Generated by Django 4.2.9 on 2024-04-09 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdosgallery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='order',
            field=models.IntegerField(default=10),
        ),
    ]
