# Generated by Django 4.2.9 on 2024-04-09 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdosgallery', '0002_character_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='icon',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
