# Generated by Django 4.2.9 on 2024-04-11 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdosgallery', '0003_character_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='site',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
