# Generated by Django 4.2.9 on 2024-01-30 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Project title', max_length=255)),
                ('slug', models.CharField(editable=False, help_text='Project slug', max_length=255)),
                ('category', models.CharField(choices=[('game', 'Game'), ('bot', 'Bot'), ('website', 'Website'), ('doodle', 'Doodle'), ('tool', 'Tool'), ('art', 'Art'), ('blog', 'Blog'), ('misc', 'Misc.')], max_length=32)),
            ],
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
