# Generated by Django 4.2.9 on 2024-01-30 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_project_delete_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='external_url',
            field=models.URLField(blank=True, default='', max_length=255),
        ),
    ]
