# Generated by Django 4.2.1 on 2024-11-06 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_project_description_project_show_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='preview_image',
            field=models.CharField(blank=True, default='pokyfriends.gif', max_length=255),
        ),
    ]
