# Generated by Django 4.2.1 on 2024-11-09 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_project_preview_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['title']},
        ),
    ]
