# Generated by Django 4.2.9 on 2024-09-14 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100)),
                ('summary', models.CharField(max_length=250)),
                ('css', models.TextField(blank=True, default='')),
                ('content', models.TextField()),
                ('source', models.URLField(blank=True, default='')),
                ('privacy', models.IntegerField(choices=[(1, 'Public'), (2, 'Unlisted'), (3, 'Password Protected'), (4, 'Private')], default=1)),
                ('schema', models.IntegerField(choices=[(1, 'HTML'), (2, 'Markdown')], default=1)),
                ('static_directory', models.CharField(blank=True, default='', help_text='Name of directory where static files for this post are stored', max_length=120)),
                ('password', models.CharField(blank=True, default='', max_length=32)),
                ('date', models.DateTimeField()),
                ('modification_date', models.DateTimeField(auto_now=True, help_text='Date DB entry was last modified')),
                ('revision_date', models.DateTimeField(blank=True, default=None, help_text='Date article content was last revised', null=True)),
                ('revision_details', models.TextField(blank=True, default='', help_text='Reference for revisions made to the article')),
                ('tags', models.ManyToManyField(to='cdosblog.tag')),
            ],
            options={
                'ordering': ('-date',),
            },
        ),
    ]
