# Generated by Django 4.2.9 on 2024-09-16 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdosblog', '0002_post_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=100),
        ),
    ]
