# Generated by Django 4.2.9 on 2024-09-21 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdosblog', '0004_icon_post_current_mood_post_current_music_post_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='warnings',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
