# Generated by Django 4.2.9 on 2024-09-22 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdosblog', '0005_post_warnings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='schema',
            field=models.IntegerField(choices=[(3, 'Django'), (1, 'HTML'), (2, 'Markdown')], default=1),
        ),
    ]
