# Generated by Django 4.2.9 on 2024-09-22 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdosblog', '0006_alter_post_schema'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='static_directory',
        ),
        migrations.AddField(
            model_name='post',
            name='account',
            field=models.CharField(default='dr-dos', max_length=32),
        ),
    ]
