# Generated by Django 4.2.9 on 2024-09-22 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdosblog', '0007_remove_post_static_directory_post_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='preview_extension',
            field=models.CharField(default='.png', max_length=5),
        ),
    ]
