# Generated by Django 4.2.1 on 2024-09-25 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdosblog', '0008_post_preview_extension'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='icon',
            options={'ordering': ['title']},
        ),
        migrations.AddField(
            model_name='post',
            name='django_add_ons',
            field=models.CharField(choices=[('zzt_tags', 'ZZT Tags (scroll, zzt_img)')], help_text='Additional template tag/filter libraries to include', max_length=32, null=True),
        ),
    ]
