# Generated by Django 4.2.1 on 2024-09-27 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdosblog', '0009_alter_icon_options_post_django_add_ons'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='django_add_ons',
            field=models.CharField(blank=True, choices=[('zzt_tags', 'ZZT Tags (scroll, zzt_img)')], help_text='Additional template tag/filter libraries to include', max_length=32, null=True),
        ),
    ]
