# Generated by Django 4.2.1 on 2024-11-06 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cdosblog', '0011_alter_post_slug_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='icon',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='cdosblog.icon'),
        ),
        migrations.AlterField(
            model_name='post',
            name='privacy',
            field=models.IntegerField(choices=[(0, 'Draft'), (1, 'Public'), (2, 'Unlisted'), (3, 'Password Protected'), (4, 'Private')], default=1),
        ),
    ]
