# Generated by Django 5.2 on 2025-09-03 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdosblog', '0012_alter_post_icon_alter_post_privacy'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField()),
                ('visible', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now=True)),
                ('pokemon_icon', models.IntegerField(default=25)),
                ('name', models.CharField(max_length=100)),
                ('content', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='icon',
            name='filename',
            field=models.CharField(help_text='/static/cdosblog/icons/<this.gif>', max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='schema',
            field=models.IntegerField(choices=[(3, 'Django'), (1, 'HTML'), (2, 'Markdown'), (4, 'LiveJournal')], default=2),
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(default='-', max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='summary',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
        migrations.AddField(
            model_name='post',
            name='comments',
            field=models.ManyToManyField(to='cdosblog.comment'),
        ),
    ]
